const shopId = localStorage.getItem('shopId');
export const shopCollection = 'shops';
export const userCollection = 'users';
export const categoryCollection = 'categories';
export const itemCol = 'items';
export const shopItemCol = `${shopCollection}/${shopId!}/items`;
export const shopArchiveCol = `${shopCollection}/${shopId!}/archives`;
export const shopSaleCol = `${shopCollection}/${shopId!}/sales`;
export const shopPurchaseCol = `${shopCollection}/${shopId!}/purchases`;
